server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  profiles:
    active: default  # Se você não tiver um perfil 'native'
  data:
    mongodb:
      uri: mongodb+srv://Kaique:123@cluster0.c54by.mongodb.net/cliente?retryWrites=true&w=majority&appName=Cluster0
      database: cliente
      auto-index-creation: true

application-version: 1.0
