server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb+srv://Kaique:123@cluster0.c54by.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        database: produto
        auto-index-creation: true
